/////////////////////////////////////////////////////////////////////////////
// Name:        dialog_config_panel.h
// Purpose:
// Author:      Rex Zhang
// Modified by:
// Created:     07/02/2006 17:00:41
// RCS-ID:
// Copyright:   cooooooooooooopy
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 07/02/2006 17:00:41

#ifndef _DIALOG_CONFIG_PANEL_H_
#define _DIALOG_CONFIG_PANEL_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "dialog_config_panel.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
#include "wx/notebook.h"
#include "wx/datectrl.h"
////@end includes

#include "common_config.h"

#include "wx/dateevt.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxDatePickerCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_FRAME_MAIN 10000
#define SYMBOL_DIALOG_CONFIG_PANEL_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxMINIMIZE_BOX|wxMAXIMIZE_BOX|wxCLOSE_BOX
#define SYMBOL_DIALOG_CONFIG_PANEL_TITLE _("National Geographic Photo Of the Day Wallpaper Control Center")
#define SYMBOL_DIALOG_CONFIG_PANEL_IDNAME ID_FRAME_MAIN
#define SYMBOL_DIALOG_CONFIG_PANEL_SIZE wxSize(640, 470)
#define SYMBOL_DIALOG_CONFIG_PANEL_POSITION wxDefaultPosition
#define ID_PANEL 10001
#define ID_NOTEBOOK 10002
#define ID_PANEL1 10003
#define ID_CHOICE 10034
#define ID_CHECKBOX 10013
#define ID_CHECKBOX1 10014
#define ID_CHOICE2 10035
#define ID_BUTTON3 10036
#define ID_PANEL2 10004
#define ID_CHECKBOX2 10026
#define ID_PANEL3 10005
#define ID_CHOICE1 10027
#define ID_BUTTON1 10028
#define ID_TEXTCTRL4 10018
#define ID_TEXTCTRL5 10019
#define ID_TEXTCTRL6 10020
#define ID_BUTTON 10021
#define ID_TEXTCTRL3 10022
#define ID_BUTTON2 10015
#define ID_PANEL5 10030
#define ID_TEXTCTRL7 10031
#define ID_BUTTON_LocalPicturePath 10032
#define ID_PANEL6 10033
#define ID_TEXTCTRL 10010
#define ID_BUTTON_PodBasePath 10011
#define ID_TEXTCTRL1 10012
#define ID_TEXTCTRL2 10029
#define ID_DATECTRL 10016
#define ID_BUTTON_RELOAD_CONFIG 10006
#define ID_BUTTON_RESTORE_DEFAULT 10007
#define ID_BUTTON_SAVE_CONFIG 10017
#define ID_BUTTON_ABOUT 10008
#define ID_BUTTON_QUIT 10009
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * dialog_config_panel class declaration
 */

class dialog_config_panel: public wxFrame
{
    DECLARE_CLASS( dialog_config_panel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    dialog_config_panel( );
    dialog_config_panel( wxWindow* parent, wxWindowID id = SYMBOL_DIALOG_CONFIG_PANEL_IDNAME, const wxString& caption = SYMBOL_DIALOG_CONFIG_PANEL_TITLE, const wxPoint& pos = SYMBOL_DIALOG_CONFIG_PANEL_POSITION, const wxSize& size = SYMBOL_DIALOG_CONFIG_PANEL_SIZE, long style = SYMBOL_DIALOG_CONFIG_PANEL_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DIALOG_CONFIG_PANEL_IDNAME, const wxString& caption = SYMBOL_DIALOG_CONFIG_PANEL_TITLE, const wxPoint& pos = SYMBOL_DIALOG_CONFIG_PANEL_POSITION, const wxSize& size = SYMBOL_DIALOG_CONFIG_PANEL_SIZE, long style = SYMBOL_DIALOG_CONFIG_PANEL_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin dialog_config_panel event handler declarations

    /// wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE
    void OnChoiceSelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_CHECKBOX
    void OnCheckboxClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_CHECKBOX1
    void OnCheckbox1Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE2
    void OnChoice2Selected( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON3
    void OnButton3Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_CHECKBOX2
    void OnCheckbox2Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE1
    void OnChoice1Selected( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON1
    void OnButton1Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL6
    void OnTextctrl6Updated( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON
    void OnButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL7
    void OnTextctrl7Updated( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_LocalPicturePath
    void OnButtonLocalpicturepathClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL
    void OnTextctrlUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_PodBasePath
    void OnButtonPodbasepathClick( wxCommandEvent& event );

    /// wxEVT_DATE_CHANGED event handler for ID_DATECTRL
    void OnDatectrlDateChanged( wxDateEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_RELOAD_CONFIG
    void OnButtonReloadConfigClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_RESTORE_DEFAULT
    void OnButtonRestoreDefaultClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_SAVE_CONFIG
    void OnButtonSaveConfigClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_ABOUT
    void OnButtonAboutClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_QUIT
    void OnButtonQuitClick( wxCommandEvent& event );

////@end dialog_config_panel event handler declarations

////@begin dialog_config_panel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end dialog_config_panel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin dialog_config_panel member variables
    wxChoice* PictureSource;
    wxCheckBox* PauseChangeWallpaper;
    wxCheckBox* ShowSplash;
    wxChoice* UILanguage;
    wxCheckBox* ShowDisc;
    wxChoice* ScreenWidthHeight;
    wxTextCtrl* ScreenWidth;
    wxTextCtrl* ScreenHeight;
    wxTextCtrl* ScreenPicturePath;
    wxTextCtrl* ScreenPictureName;
    wxTextCtrl* LocalPicturePath;
    wxTextCtrl* PodBasePath;
    wxTextCtrl* PodDatabaseName;
    wxTextCtrl* PodPicturePath;
    wxDatePickerCtrl* NextPODDay;
    wxButton* ButtonSaveConfig;
////@end dialog_config_panel member variables

    void InitConfig(void);
    void SetDefault(void);
    void ShowConfig(void);

    void ReadConfig(void);
    void WriteConfig(void);

    void AutoDetectScreenWH(void);
    wxString AutoDetectSystemPath(void);

    ngpodwcConfig config;
};

#endif
    // _DIALOG_CONFIG_PANEL_H_
