; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "NGPODWC"
#define MyAppVer "0.2"
#define MyAppVerName MyAppName + " v" + MyAppVer
#define MyAppPublisher "Rex Zhang(rex.zhang@gmail.com)"
#define MyAppURL "http://www.flord.net"
#define MyAppExeName "ngpodwcc_u.exe"
#define MyProjectDir "D:\My Documents\Code Blocks Studio Projects\ngpodwc"
#define wxWidgetsDir "D:\wxWidgets-2.6.2"

[Setup]
AppName={#MyAppName}
AppVerName={#MyAppVerName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
;LicenseFile=license
;InfoBeforeFile=info before
;InfoAfterFile=info after
OutputDir={#MyProjectDir}\install
OutputBaseFilename=ngpodwc_setup_v{#MyAppVer}
;SetupIconFile={#MyProjectDir}art\logo.ico
Compression=none
SolidCompression=true
VersionInfoVersion={#MyAppVer}
ShowLanguageDialog=yes
WizardImageFile=compiler:wizmodernimage-IS.bmp
WizardSmallImageFile=compiler:wizmodernsmallimage-IS.bmp
AppID={{A61D1CBA-4FFF-4FAF-A047-BF9A19EBA183}


[Languages]
Name: eng; MessagesFile: compiler:Default.isl
Name: chi; MessagesFile: compiler:Languages\ChineseSimp-11-5.1.0.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked
Name: quicklaunchicon; Description: {cm:CreateQuickLaunchIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: {#MyProjectDir}\ngpodwcc_u.exe; DestDir: {app}; Flags: ignoreversion
Source: {#MyProjectDir}\ngpodwc_u.exe; DestDir: {app}; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: {#wxWidgetsDir}\lib\gcc_dll\wxmsw26u_gcc_cb.dll; DestDir: {app}; Tasks: ; Languages: 
Source: {#MyProjectDir}\ngpod\*; DestDir: {app}\ngpod; Flags: recursesubdirs

[Icons]
Name: {group}\øÿ÷∆Ã®; Filename: {app}\{#MyAppExeName}; IconFilename: {app}\ngpodwcc_u.exe
Name: {group}\{cm:UninstallProgram,{#MyAppName}}; Filename: {uninstallexe}
Name: {userdesktop}\{#MyAppName}; Filename: {app}\{#MyAppExeName}; Tasks: desktopicon
Name: {userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}; Filename: {app}\{#MyAppExeName}; Tasks: quicklaunchicon
Name: {group}\◊¿√Ê«–ªª; Filename: {app}\ngpodwc_u.exe; IconFilename: {app}\ngpodwc_u.exe
Name: {group}\NGPODÕº∆¨œ¬‘ÿ; Filename: {app}\ngpod\ngpod.exe; IconFilename: {app}\ngpod\ngpod.exe; Tasks: ; Languages: 

[Run]
Filename: {app}\{#MyAppExeName}; Description: {cm:LaunchProgram,{#MyAppName}}; Flags: nowait postinstall skipifsilent
