/////////////////////////////////////////////////////////////////////////////
// Name:        ngpodwcc_mainframe.cpp
// Purpose:
// Author:      Rex Zhang
// Modified by:
// Created:     07/02/2006 17:00:41
// RCS-ID:
// Copyright:   cooooooooooooopy
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 07/02/2006 17:00:41

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "ngpodwcc_mainframe.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
#include "ngpodwcc_aboutdialog.h"
////@end includes

#include "ngpodwcc_mainframe.h"

////@begin XPM images
#include "art/logo32x32.xpm"
#include "art/logo60x80.xpm"
////@end XPM images

/*!
 * ngpodwcc_MainFrame type definition
 */

IMPLEMENT_CLASS( ngpodwcc_MainFrame, wxFrame )

/*!
 * ngpodwcc_MainFrame event table definition
 */

BEGIN_EVENT_TABLE( ngpodwcc_MainFrame, wxFrame )

////@begin ngpodwcc_MainFrame event table entries
    EVT_UPDATE_UI( ID_TEXTCTRL, ngpodwcc_MainFrame::OnTextctrlUpdate )

    EVT_BUTTON( ID_BUTTON_PodBasePath, ngpodwcc_MainFrame::OnButtonPodbasepathClick )

    EVT_BUTTON( ID_BUTTON_RELOAD_CONFIG, ngpodwcc_MainFrame::OnButtonReloadConfigClick )

    EVT_BUTTON( ID_BUTTON_SAVE_CONFIG, ngpodwcc_MainFrame::OnButtonSaveConfigClick )

    EVT_BUTTON( ID_BUTTON_ABOUT, ngpodwcc_MainFrame::OnButtonAboutClick )

    EVT_BUTTON( ID_BUTTON_QUIT, ngpodwcc_MainFrame::OnButtonQuitClick )

////@end ngpodwcc_MainFrame event table entries

END_EVENT_TABLE()

/*!
 * ngpodwcc_MainFrame constructors
 */

ngpodwcc_MainFrame::ngpodwcc_MainFrame( )
{}

ngpodwcc_MainFrame::ngpodwcc_MainFrame( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Create( parent, id, caption, pos, size, style );
}

/*!
 * ngpodwcc_MainFrame creator
 */

bool ngpodwcc_MainFrame::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    ////@begin ngpodwcc_MainFrame member initialisation
    PodBasePath = NULL;
    ////@end ngpodwcc_MainFrame member initialisation

    config.ReadConfig();

    ////@begin ngpodwcc_MainFrame creation
    wxFrame::Create( parent, id, caption, pos, size, style );

    CreateControls();
    SetIcon(GetIconResource(wxT("art/logo32x32.xpm")));
    Centre();
    ////@end ngpodwcc_MainFrame creation

    return true;
}

/*!
 * Control creation for ngpodwcc_MainFrame
 */

void ngpodwcc_MainFrame::CreateControls()
{
    ////@begin ngpodwcc_MainFrame content construction
    ngpodwcc_MainFrame* itemFrame1 = this;

    wxPanel* itemPanel2 = new wxPanel( itemFrame1, ID_PANEL, wxDefaultPosition, wxDefaultSize, wxNO_BORDER|wxTAB_TRAVERSAL );

    wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxVERTICAL);
    itemPanel2->SetSizer(itemBoxSizer3);

    wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer3->Add(itemBoxSizer4, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxBitmap itemStaticBitmap5Bitmap(itemFrame1->GetBitmapResource(wxT("art/logo60x80.xpm")));
    wxStaticBitmap* itemStaticBitmap5 = new wxStaticBitmap( itemPanel2, wxID_STATIC, itemStaticBitmap5Bitmap, wxDefaultPosition, wxSize(60, 80), 0 );
    itemBoxSizer4->Add(itemStaticBitmap5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText6 = new wxStaticText( itemPanel2, wxID_STATIC, _("National Geographic Photo Of the Day\nWallpaper Conterl Center"), wxDefaultPosition, wxDefaultSize, 0 );
    itemStaticText6->SetFont(wxFont(11, wxSWISS, wxNORMAL, wxBOLD, false, _T("Tahoma")));
    itemBoxSizer4->Add(itemStaticText6, 0, wxALIGN_BOTTOM|wxALL|wxADJUST_MINSIZE, 5);

    wxNotebook* itemNotebook7 = new wxNotebook( itemPanel2, ID_NOTEBOOK, wxDefaultPosition, wxDefaultSize, wxNB_TOP );

    wxPanel* itemPanel8 = new wxPanel( itemNotebook7, ID_PANEL1, wxDefaultPosition, wxDefaultSize, wxNO_BORDER|wxTAB_TRAVERSAL );
    wxFlexGridSizer* itemFlexGridSizer9 = new wxFlexGridSizer(2, 3, 0, 0);
    itemPanel8->SetSizer(itemFlexGridSizer9);

    itemFlexGridSizer9->Add(5, 5, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemFlexGridSizer9->Add(5, 5, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemFlexGridSizer9->Add(5, 5, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText13 = new wxStaticText( itemPanel8, wxID_STATIC, _("PodBasePath"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer9->Add(itemStaticText13, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    PodBasePath = new wxTextCtrl( itemPanel8, ID_TEXTCTRL, _T(""), wxDefaultPosition, wxSize(300, -1), 0 );
    itemFlexGridSizer9->Add(PodBasePath, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton15 = new wxButton( itemPanel8, ID_BUTTON_PodBasePath, _("..."), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer9->Add(itemButton15, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText16 = new wxStaticText( itemPanel8, wxID_STATIC, _("PodDatabaseName"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer9->Add(itemStaticText16, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    wxTextCtrl* itemTextCtrl17 = new wxTextCtrl( itemPanel8, ID_TEXTCTRL1, _("pod.mdb"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer9->Add(itemTextCtrl17, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton18 = new wxButton( itemPanel8, ID_BUTTON5, _("Restore Default"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer9->Add(itemButton18, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText19 = new wxStaticText( itemPanel8, wxID_STATIC, _("PodPicturePath"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer9->Add(itemStaticText19, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    wxString itemChoice20Strings[] = {
        _("POD\\pictures\\lg_wallpaper"),
        _("POD\\pictures\\/n\normal\n")
    };
    wxChoice* itemChoice20 = new wxChoice( itemPanel8, ID_CHOICE, wxDefaultPosition, wxDefaultSize, 2, itemChoice20Strings, 0 );
    itemChoice20->SetStringSelection(_("POD\\pictures\\lg_wallpaper"));
    itemFlexGridSizer9->Add(itemChoice20, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton21 = new wxButton( itemPanel8, ID_BUTTON6, _("Restore Default"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer9->Add(itemButton21, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText22 = new wxStaticText( itemPanel8, wxID_STATIC, _("Next POD Day"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer9->Add(itemStaticText22, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    wxDatePickerCtrl* itemDatePickerCtrl23 = new wxDatePickerCtrl( itemPanel8, ID_DATECTRL, wxDateTime(), wxDefaultPosition, wxDefaultSize, wxDP_DROPDOWN|wxDP_DEFAULT );
    wxDateTime minDateitemDatePickerCtrl23(1, (wxDateTime::Month) 2, 2001);
    wxDateTime maxDateitemDatePickerCtrl23;
    itemDatePickerCtrl23->SetRange(minDateitemDatePickerCtrl23, maxDateitemDatePickerCtrl23);
    itemFlexGridSizer9->Add(itemDatePickerCtrl23, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton24 = new wxButton( itemPanel8, ID_BUTTON9, _("Restore Default"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer9->Add(itemButton24, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemFlexGridSizer9->Add(5, 5, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemFlexGridSizer9->Add(5, 5, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemNotebook7->AddPage(itemPanel8, _("NGPOD Source Setting"));

    wxPanel* itemPanel27 = new wxPanel( itemNotebook7, ID_PANEL2, wxDefaultPosition, wxDefaultSize, wxNO_BORDER|wxTAB_TRAVERSAL );
    wxStaticText* itemStaticText28 = new wxStaticText( itemPanel27, wxID_STATIC, _("Comming soon..."), wxDefaultPosition, wxDefaultSize, 0 );

    itemNotebook7->AddPage(itemPanel27, _("Image Convert Setting"));

    wxPanel* itemPanel29 = new wxPanel( itemNotebook7, ID_PANEL3, wxDefaultPosition, wxDefaultSize, wxNO_BORDER|wxTAB_TRAVERSAL );
    wxFlexGridSizer* itemFlexGridSizer30 = new wxFlexGridSizer(2, 2, 0, 0);
    itemPanel29->SetSizer(itemFlexGridSizer30);

    itemFlexGridSizer30->Add(5, 5, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemFlexGridSizer30->Add(5, 5, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText33 = new wxStaticText( itemPanel29, wxID_STATIC, _("Screen Width x Height"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer30->Add(itemStaticText33, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    wxString itemComboBox34Strings[] = {
        _("640x480"),
        _("800x600"),
        _("1024x768"),
        _("couuuuuuuu")
    };
    wxComboBox* itemComboBox34 = new wxComboBox( itemPanel29, ID_COMBOBOX, _("800x600"), wxDefaultPosition, wxDefaultSize, 4, itemComboBox34Strings, wxCB_READONLY );
    itemComboBox34->SetStringSelection(_("800x600"));
    itemFlexGridSizer30->Add(itemComboBox34, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText35 = new wxStaticText( itemPanel29, wxID_STATIC, _("Screen Width"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer30->Add(itemStaticText35, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    wxTextCtrl* itemTextCtrl36 = new wxTextCtrl( itemPanel29, ID_TEXTCTRL4, _T(""), wxDefaultPosition, wxDefaultSize, 0 );
    itemTextCtrl36->Enable(false);
    itemFlexGridSizer30->Add(itemTextCtrl36, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText37 = new wxStaticText( itemPanel29, wxID_STATIC, _("Screen Height"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer30->Add(itemStaticText37, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    wxTextCtrl* itemTextCtrl38 = new wxTextCtrl( itemPanel29, ID_TEXTCTRL5, _T(""), wxDefaultPosition, wxDefaultSize, 0 );
    itemTextCtrl38->Enable(false);
    itemFlexGridSizer30->Add(itemTextCtrl38, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText39 = new wxStaticText( itemPanel29, wxID_STATIC, _("ScreenPicturePath"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer30->Add(itemStaticText39, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    wxTextCtrl* itemTextCtrl40 = new wxTextCtrl( itemPanel29, ID_TEXTCTRL6, _("C:\\WINNT"), wxDefaultPosition, wxSize(200, -1), wxTE_READONLY );
    itemFlexGridSizer30->Add(itemTextCtrl40, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText41 = new wxStaticText( itemPanel29, wxID_STATIC, _("ScreenPictureName"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer30->Add(itemStaticText41, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL|wxADJUST_MINSIZE, 5);

    wxTextCtrl* itemTextCtrl42 = new wxTextCtrl( itemPanel29, ID_TEXTCTRL3, _("POD_Wallpaper.bmp"), wxDefaultPosition, wxSize(200, -1), wxTE_READONLY );
    itemFlexGridSizer30->Add(itemTextCtrl42, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemFlexGridSizer30->Add(5, 5, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemFlexGridSizer30->Add(5, 5, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemNotebook7->AddPage(itemPanel29, _("Screen Info Setting"));

    itemBoxSizer3->Add(itemNotebook7, 0, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer45 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer3->Add(itemBoxSizer45, 0, wxALIGN_LEFT|wxALL, 5);

    wxButton* itemButton46 = new wxButton( itemPanel2, ID_BUTTON_RELOAD_CONFIG, _("Reload Config"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer45->Add(itemButton46, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton47 = new wxButton( itemPanel2, ID_BUTTON_RESTORE_DEFAULT, _("Restore Default"), wxDefaultPosition, wxDefaultSize, 0 );
    itemButton47->Enable(false);
    itemBoxSizer45->Add(itemButton47, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton48 = new wxButton( itemPanel2, ID_BUTTON_SAVE_CONFIG, _("Save Config"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer45->Add(itemButton48, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticLine* itemStaticLine49 = new wxStaticLine( itemPanel2, wxID_STATIC, wxDefaultPosition, wxDefaultSize, wxLI_VERTICAL );
    itemBoxSizer3->Add(itemStaticLine49, 0, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer50 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer3->Add(itemBoxSizer50, 0, wxALIGN_RIGHT|wxALL, 5);

    wxButton* itemButton51 = new wxButton( itemPanel2, ID_BUTTON_ABOUT, _("About"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer50->Add(itemButton51, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton52 = new wxButton( itemPanel2, ID_BUTTON_QUIT, _("Quit"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer50->Add(itemButton52, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    ////@end ngpodwcc_MainFrame content construction
}

/*!
 * Should we show tooltips?
 */

bool ngpodwcc_MainFrame::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap ngpodwcc_MainFrame::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
    ////@begin ngpodwcc_MainFrame bitmap retrieval
    wxUnusedVar(name);
    if (name == _T("art/logo60x80.xpm"))
    {
        wxBitmap bitmap( logo60x80_xpm);
        return bitmap;
    }
    return wxNullBitmap;
    ////@end ngpodwcc_MainFrame bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon ngpodwcc_MainFrame::GetIconResource( const wxString& name )
{
    // Icon retrieval
    ////@begin ngpodwcc_MainFrame icon retrieval
    wxUnusedVar(name);
    if (name == _T("art/logo32x32.xpm"))
    {
        wxIcon icon( logo32x32_xpm);
        return icon;
    }
    return wxNullIcon;
    ////@end ngpodwcc_MainFrame icon retrieval
}
/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON2
 */

void ngpodwcc_MainFrame::OnButtonAboutClick( wxCommandEvent& event )
{
    ////@begin wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON2 in ngpodwcc_MainFrame.
    // Before editing this code, remove the block markers.
    ngpodwcc_aboutdialog* window = new ngpodwcc_aboutdialog(NULL, ID_DIALOG_ABOUT, _("Dialog"));
    window->Show(true);
    ////@end wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON2 in ngpodwcc_MainFrame.
}


/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON3
 */

void ngpodwcc_MainFrame::OnButtonQuitClick( wxCommandEvent& event )
{
    ////@begin wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON3 in ngpodwcc_MainFrame.
    // Before editing this code, remove the block markers.
    Destroy();
    ////@end wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON3 in ngpodwcc_MainFrame.
}


/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON4
 */

void ngpodwcc_MainFrame::OnButtonPodbasepathClick( wxCommandEvent& event )
{
    ////@begin wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON4 in ngpodwcc_MainFrame.
    // Before editing this code, remove the block markers.
    //event.Skip();
    wxString defaultPath = wxT("");
    wxDirDialog dialog(NULL,wxT("Testing directory picker"),defaultPath, wxDD_NEW_DIR_BUTTON);
    if (dialog.ShowModal() == wxID_OK)
    {
        wxString path = dialog.GetPath();
        wxMessageBox(path);
    }
    ////@end wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON4 in ngpodwcc_MainFrame.
}


/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_RELOAD_CONFIG
 */

void ngpodwcc_MainFrame::OnButtonReloadConfigClick( wxCommandEvent& event )
{
////@begin wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_RELOAD_CONFIG in ngpodwcc_MainFrame.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_RELOAD_CONFIG in ngpodwcc_MainFrame.
}


/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_SAVE_CONFIG
 */

void ngpodwcc_MainFrame::OnButtonSaveConfigClick( wxCommandEvent& event )
{
////@begin wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_SAVE_CONFIG in ngpodwcc_MainFrame.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_SAVE_CONFIG in ngpodwcc_MainFrame.
}


/*!
 * wxEVT_UPDATE_UI event handler for ID_TEXTCTRL
 */

void ngpodwcc_MainFrame::OnTextctrlUpdate( wxUpdateUIEvent& event )
{
    PodBasePath->SetValue(config.PodBasePath);
////@begin wxEVT_UPDATE_UI event handler for ID_TEXTCTRL in ngpodwcc_MainFrame.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_UPDATE_UI event handler for ID_TEXTCTRL in ngpodwcc_MainFrame. 
    
}


