/////////////////////////////////////////////////////////////////////////////
// Name:        dialog_config_panel.h
// Purpose:
// Author:      Rex Zhang
// Modified by:
// Created:     07/02/2006 17:00:41
// RCS-ID:
// Copyright:   (c) 2006 Rex Zhang
// Licence:     GNU General Public License (GPL) version 2
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 07/02/2006 17:00:41

#ifndef _DIALOG_CONFIG_PANEL_H_
#define _DIALOG_CONFIG_PANEL_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "dialog_config_panel.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
#include "wx/notebook.h"
#include "wx/datectrl.h"
////@end includes

#include "common_config.h"

#include "wx/dateevt.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxDatePickerCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG_CONFIG_PANEL 11000
#define SYMBOL_DIALOG_CONFIG_PANEL_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxMINIMIZE_BOX|wxMAXIMIZE_BOX|wxCLOSE_BOX
#define SYMBOL_DIALOG_CONFIG_PANEL_TITLE _("National Geographic Photo Of the Day Wallpaper Control Center")
#define SYMBOL_DIALOG_CONFIG_PANEL_IDNAME ID_DIALOG_CONFIG_PANEL
#define SYMBOL_DIALOG_CONFIG_PANEL_SIZE wxSize(640, 470)
#define SYMBOL_DIALOG_CONFIG_PANEL_POSITION wxDefaultPosition
#define ID_PANEL 11001
#define ID_NOTEBOOK 11002
#define ID_PANEL1 11003
#define ID_CHOICE 11004
#define ID_CHECKBOX 11005
#define ID_CHECKBOX1 11006
#define ID_CHOICE2 11007
#define ID_BUTTON3 11008
#define ID_PANEL2 11009
#define ID_CHECKBOX2 11010
#define ID_PANEL3 11011
#define ID_CHOICE1 11012
#define ID_BUTTON1 11013
#define ID_TEXTCTRL4 11014
#define ID_TEXTCTRL5 11015
#define ID_TEXTCTRL6 11016
#define ID_BUTTON 11017
#define ID_TEXTCTRL3 11018
#define ID_BUTTON2 11019
#define ID_PANEL5 11020
#define ID_TEXTCTRL7 11021
#define ID_BUTTON4 11022
#define ID_PANEL6 11023
#define ID_TEXTCTRL 11024
#define ID_BUTTON5 11025
#define ID_TEXTCTRL1 11026
#define ID_TEXTCTRL2 11027
#define ID_DATEPICKERCTRL 11028
#define ID_BUTTON6 11029
#define ID_BUTTON7 11030
#define ID_BUTTON9 11031
#define ID_BUTTON10 11032
#define ID_BUTTON11 11033
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * dialog_config_panel class declaration
 */

class dialog_config_panel: public wxFrame
{
    DECLARE_CLASS( dialog_config_panel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    dialog_config_panel( );
    dialog_config_panel( wxWindow* parent, wxWindowID id = SYMBOL_DIALOG_CONFIG_PANEL_IDNAME, const wxString& caption = SYMBOL_DIALOG_CONFIG_PANEL_TITLE, const wxPoint& pos = SYMBOL_DIALOG_CONFIG_PANEL_POSITION, const wxSize& size = SYMBOL_DIALOG_CONFIG_PANEL_SIZE, long style = SYMBOL_DIALOG_CONFIG_PANEL_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DIALOG_CONFIG_PANEL_IDNAME, const wxString& caption = SYMBOL_DIALOG_CONFIG_PANEL_TITLE, const wxPoint& pos = SYMBOL_DIALOG_CONFIG_PANEL_POSITION, const wxSize& size = SYMBOL_DIALOG_CONFIG_PANEL_SIZE, long style = SYMBOL_DIALOG_CONFIG_PANEL_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin dialog_config_panel event handler declarations

    /// wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE
    void OnChoiceSelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_CHECKBOX
    void OnCheckboxClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_CHECKBOX1
    void OnCheckbox1Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE2
    void OnChoice2Selected( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON3
    void OnButton3Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_CHECKBOX2
    void OnCheckbox2Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE1
    void OnChoice1Selected( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON1
    void OnButton1Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL6
    void OnTextctrl6Updated( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON
    void OnButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL7
    void OnTextctrl7Updated( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON4
    void OnButtonLocalpicturepathClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL
    void OnTextctrlUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON5
    void OnButtonPodbasepathClick( wxCommandEvent& event );

    /// wxEVT_DATE_CHANGED event handler for ID_DATEPICKERCTRL
    void OnDatectrlDateChanged( wxDateEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON6
    void OnButtonReloadConfigClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON7
    void OnButtonRestoreDefaultClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON9
    void OnButtonSaveConfigClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON10
    void OnButtonAboutClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON11
    void OnButtonQuitClick( wxCommandEvent& event );

////@end dialog_config_panel event handler declarations

////@begin dialog_config_panel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end dialog_config_panel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin dialog_config_panel member variables
    wxChoice* PictureSource;
    wxCheckBox* PauseChangeWallpaper;
    wxCheckBox* ShowSplash;
    wxChoice* UILanguage;
    wxCheckBox* ShowDisc;
    wxChoice* ScreenWidthHeight;
    wxTextCtrl* ScreenWidth;
    wxTextCtrl* ScreenHeight;
    wxTextCtrl* ScreenPicturePath;
    wxTextCtrl* ScreenPictureName;
    wxTextCtrl* LocalPicturePath;
    wxTextCtrl* PodBasePath;
    wxTextCtrl* PodDatabaseName;
    wxTextCtrl* PodPicturePath;
    wxDatePickerCtrl* NextPODDay;
    wxButton* ButtonSaveConfig;
////@end dialog_config_panel member variables

    void InitConfig(void);
    void SetDefault(void);
    void ShowConfig(void);

    void ReadConfig(void);
    void WriteConfig(void);

    void AutoDetectScreenWH(void);
    wxString AutoDetectSystemPath(void);

    ngpodwcConfig config;
};

#endif
    // _DIALOG_CONFIG_PANEL_H_
